export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const RETRIEVE_USERS_SUCCESS = 'RETRIEVE_USERS_SUCCESS';
export const RETRIEVE_USER_SUCCESSS = 'GET_USER_SUCCESSS';
export const SET_CHOSEN_USER = 'SET_CHOSEN_USER';
export const DISPLAY_CHOSEN_USER = 'DISPLAY_CHOSEN_USER';
export const DELETE_CHOSEN_USER = 'DELETE_CHOSEN_USER';

export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const LOAD_DOCUMENT_SUCCESS = 'LOAD_DOCUMENT_SUCCESS';
export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';
export const DELETE_DOCUMENT_SUCCESS = 'DELETE_DOCUMENT_SUCCESS';
export const CHOOSE_AS_CURRENT_DOCUMENT = 'CHOOSE_AS_CURRENT_DOCUMENT';

export const LOAD_ROLE_SUCCESS = 'LOAD_ROLE_SUCCESS';
export const SET_CURRENT_ROLE = 'SET_CURRENT_ROLE';
export const DELETE_CURRENT_ROLE = 'DELETE_CURRENT_ROLE';





